import HOD from '../models/hod.model.js';
import Section from '../models/section.model.js';
import Hostel from '../models/hostel.model.js';
import Mentor from '../models/mentor.model.js';
import UMC from '../models/umc.model.js';
import Course from '../models/course.model.js';
import Student from '../models/student.model.js';
import TGPA from '../models/tgpa.model.js';
import HourSlot from '../models/hour-slot.model.js';
import Query from '../models/query.model.js';
import TrainingQuery from '../models/training-query.model.js';
import Department from '../models/department.model.js';
import Subject from '../models/subject.model.js';
import CourseSubject from '../models/course-subject.model.js';
import Faculty from '../models/faculty.model.js';
import Lecture from '../models/lecture.model.js';
import Attendance from '../models/attendance.model.js';
import OverallAttendance from '../models/overall-attendance.model.js';
import Result from '../models/result.model.js';

// await HOD.sync({ alter: true });
// await Section.sync();
// await Hostel.sync({ force: true });
// await Mentor.sync({ force: true });
// await UMC.sync({ force: true });
// await Course.sync({ alter: true });
// await Student.sync({ force: true });
// await TGPA.sync({ force: true });
// await HourSlot.sync();
// await Query.sync({ force: true });
// await TrainingQuery.sync({ force: true });
// await Department.sync();
// await Subject.sync({ alter: true });
// await CourseSubject.sync({ force: true });
// await Faculty.sync();
// await Lecture.sync();
// await Attendance.sync({ alter: true });
// await OverallAttendance.sync({ force: true });
// await Result.sync({ force: true });
